### ISSUE TITLE
Cargo fmt

### ISSUE THREAD

**Issue by bovee** [onecodex/needletail#17]
We have ~223 lines that get changed when running this so we should probably make sure our style is more consistent with the standard going forward.

**Comment by luizirber** [comment]
I set up [`rust-vim`][1] to autoformat code when I save it, there are similar solutions for [other editors][2].

[1]: https://github.com/rust-lang/rust.vim#formatting-with-rustfmt
[2]: https://github.com/rust-lang-nursery/rustfmt#running-rustfmt-from-your-editor

**Comment by luizirber** [comment]
yes, the `let g:rustfmt_autosave = 1` comes from `rust-vim`.

I think the CircleCI test is good to avoid getting unformatted code into `master`, but it is a bit annoying to go back and reformat the code after tests fail. The `git commit` hook is good because it doesn't even let you commit the code.

(I have a `git commit` hook set up with `black` for Python in another codebase, but didn't find a good one for Rust yet)

**Comment by bovee** [comment]
As of 1f5ac3a24849dd8fd119609ab571a9ba5c4345d6 we now run `cargo fmt` and `cargo clippy` on CI.
